<?php


return [
    'company' => [
        'name' => 'Company Name',
        'address' => 'Adress',
        'address_2' => 'Adress 2',
        'postcode' => 'Postcode',
        'city' => 'City',
        'company_no' => 'Company No.',
        'vat_no' => 'Company Registration Number',
        'bank_account' => 'Bank Account',
        'bank_name' => 'Bank Name',
        'iban' => 'IBAN',
        'bic' => 'BIC',

    ],
    'contacts' => [
        'type' => 'Contact Type',
        'firstname' => 'Firstname',
        'lastname' => 'Lastname',
        'position' => 'Position ',
        'email' => 'Email ',
        'phone' => 'Phone',
    ],
    'financial_information' => [
        'mod_sales' => 'Sales',
        'disc_sales' => 'Discount Sales',
        'mod_engine' => 'Engine',
        'disc_engine' => 'Discount Engine',
        'mod_global' => 'Global',
        'disc_global' => 'Discount Global',
        'disc_granted' => 'When is the discount granted',
        'credit_terms' => 'Credit Terms',
        'vat_to_disc' => 'VAT applied to the discount',
        'vat_to_card' => 'VAT applied to the gift card itself',
        'settlement_mode' => 'How is the settlement made',
        'payment_mode' => 'How should we pay',
        'remark' => 'Remarks'
    ],
    'giftcard_details' => [
        'name' => 'Card Name',
        'dist_site' => 'x',
        'dist_type' => 'dist_type',
        'delivery_channel' => 'delivery_channel',
        'processor' => 'processor',
        'ordering_api' => 'ordering_api',
        'has_min_req' => 'has_min_req',
        'min_req_val' => 'min_req_val',
        'card_formats' => 'card_formats',
        'val_per_api' => 'val_per_api',
        'pin_on_card' => 'pin_on_card',
        'redeem_per_trans' => 'redeem_per_trans',
        'fixed_denom' => 'fixed_denom',
        'min_denom' => 'min_denom',
        'max_denom' => 'max_denom',
        'avail_denom' => 'avail_denom',
        'point_of_redeeming' => 'point_of_redeeming',
        'multiple_country_redeeming' => 'multiple_country_redeeming',
        'countries_redeem_in' => 'countries_redeem_in',
        'abil_check_balance' => 'abil_check_balance',
        'balance_check' => 'balance_check',
        'contact_to_block' => 'contact_to_block',
        'replacement_type' => 'replacement_type',
        'has_exp_date' => 'has_exp_date',
        'validity_in_month' => 'validity_in_month',
        'validity_starts_from' => 'validity_starts_from',
        'templ_provided_by' => 'templ_provided_by',
        'template_barcode_type' => 'template_barcode_type',
    ],
    'marketing_material' => [
        'slogan'=>'slogan',
        'about'=>'about',
        'practical_info'=>'practical_info',
        'allow_adword_campaign'=>'allow_adword_campaign',
        'customer_text'=>'customer_text',
        'customer_info'=>'customer_info',
        'remark'=>'remark',
        ]
];

